packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  msgpackr-extract: true
  unrs-resolver: true

onlyBuiltDependencies:
  - bcrypt
  - esbuild
  - msgpackr-extract
  - msw
  - sharp
  - unrs-resolver
  - workerd
