insert into meta.currencies (code, name, symbol)
values
  ('AAD', 'Antarctican dollar', '$'),
  ('AED', 'United Arab Emirates dirham', 'إ.د'),
  ('AFN', 'Afghan afghani', '؋'),
  ('ALL', 'Albanian lek', 'Lek'),
  ('AMD', 'Armenian dram', '֏'),
  ('ANG', 'Netherlands Antillean guilder', 'ƒ'),
  ('AOA', 'Angolan kwanza', 'Kz'),
  ('ARS', 'Argentine peso', '$'),
  ('AUD', 'Australian dollar', '$'),
  ('AWG', 'Aruban florin', 'ƒ'),
  ('AZN', 'Azerbaijani manat', 'm'),
  ('BAM', 'Bosnia and Herzegovina convertible mark', 'KM'),
  ('BBD', 'Barbadian dollar', 'Bds$'),
  ('BDT', 'Bangladeshi taka', '৳'),
  ('BGN', 'Bulgarian lev', 'Лв.'),
  ('BHD', 'Bahraini dinar', '.د.ب'),
  ('BIF', 'Burundian franc', 'FBu'),
  ('BMD', 'Bermudian dollar', '$'),
  ('BND', 'Brunei dollar', 'B$'),
  ('BOB', 'Bolivian boliviano', 'Bs.'),
  ('BRL', 'Brazilian real', 'R$'),
  ('BSD', 'Bahamian dollar', 'B$'),
  ('BTN', 'Bhutanese ngultrum', 'Nu.'),
  ('BWP', 'Botswana pula', 'P'),
  ('BYN', 'Belarusian ruble', 'Br'),
  ('BZD', 'Belize dollar', '$'),
  ('CAD', 'Canadian dollar', '$'),
  ('CDF', 'Congolese Franc', 'FC'),
  ('CHF', 'Swiss franc', 'CHf'),
  ('CLP', 'Chilean peso', '$'),
  ('CNY', 'Chinese yuan', '¥'),
  ('COP', 'Colombian peso', '$'),
  ('CRC', 'Costa Rican colón', '₡'),
  ('CUP', 'Cuban peso', '$'),
  ('CVE', 'Cape Verdean escudo', '$'),
  ('CZK', 'Czech koruna', 'Kč'),
  ('DJF', 'Djiboutian franc', 'Fdj'),
  ('DKK', 'Danish krone', 'Kr.'),
  ('DOP', 'Dominican peso', '$'),
  ('DZD', 'Algerian dinar', 'دج'),
  ('EGP', 'Egyptian pound', 'ج.م'),
  ('ERN', 'Eritrean nakfa', 'Nfk'),
  ('ETB', 'Ethiopian birr', 'Nkf'),
  ('EUR', 'Euro', '€'),
  ('FJD', 'Fijian dollar', 'FJ$'),
  ('FKP', 'Falkland Islands pound', '£'),
  ('GBP', 'British pound', '£'),
  ('GEL', 'Georgian lari', 'ლ'),
  ('GHS', 'Ghanaian cedi', 'GH₵'),
  ('GIP', 'Gibraltar pound', '£'),
  ('GMD', 'Gambian dalasi', 'D'),
  ('GNF', 'Guinean franc', 'FG'),
  ('GTQ', 'Guatemalan quetzal', 'Q'),
  ('GYD', 'Guyanese dollar', '$'),
  ('HKD', 'Hong Kong dollar', '$'),
  ('HNL', 'Honduran lempira', 'L'),
  ('HTG', 'Haitian gourde', 'G'),
  ('HUF', 'Hungarian forint', 'Ft'),
  ('IDR', 'Indonesian rupiah', 'Rp'),
  ('ILS', 'Israeli new shekel', '₪'),
  ('INR', 'Indian rupee', '₹'),
  ('IQD', 'Iraqi dinar', 'د.ع'),
  ('IRR', 'Iranian rial', '﷼'),
  ('ISK', 'Icelandic króna', 'ko'),
  ('JMD', 'Jamaican dollar', 'J$'),
  ('JOD', 'Jordanian dinar', 'ا.د'),
  ('JPY', 'Japanese yen', '¥'),
  ('KES', 'Kenyan shilling', 'KSh'),
  ('KGS', 'Kyrgyzstani som', 'лв'),
  ('KHR', 'Cambodian riel', 'KHR'),
  ('KMF', 'Comorian franc', 'CF'),
  ('KPW', 'North Korean Won', '₩'),
  ('KRW', 'Won', '₩'),
  ('KWD', 'Kuwaiti dinar', 'ك.د'),
  ('KYD', 'Cayman Islands dollar', '$'),
  ('KZT', 'Kazakhstani tenge', 'лв'),
  ('LAK', 'Lao kip', '₭'),
  ('LBP', 'Lebanese pound', '£'),
  ('LKR', 'Sri Lankan rupee', 'Rs'),
  ('LRD', 'Liberian dollar', '$'),
  ('LSL', 'Lesotho loti', 'L'),
  ('LYD', 'Libyan dinar', 'د.ل'),
  ('MAD', 'Moroccan dirham', 'DH'),
  ('MDL', 'Moldovan leu', 'L'),
  ('MGA', 'Malagasy ariary', 'Ar'),
  ('MKD', 'Denar', 'ден'),
  ('MMK', 'Burmese kyat', 'K'),
  ('MNT', 'Mongolian tögrög', '₮'),
  ('MOP', 'Macanese pataca', '$'),
  ('MRU', 'Mauritanian ouguiya', 'UM'),
  ('MUR', 'Mauritian rupee', '₨'),
  ('MVR', 'Maldivian rufiyaa', 'Rf'),
  ('MWK', 'Malawian kwacha', 'MK'),
  ('MXN', 'Mexican peso', '$'),
  ('MYR', 'Malaysian ringgit', 'RM'),
  ('MZN', 'Mozambican metical', 'MT'),
  ('NAD', 'Namibian dollar', '$'),
  ('NGN', 'Nigerian naira', '₦'),
  ('NIO', 'Nicaraguan córdoba', 'C$'),
  ('NOK', 'Norwegian krone', 'ko'),
  ('NPR', 'Nepalese rupee', '₨'),
  ('NZD', 'New Zealand dollar', '$'),
  ('OMR', 'Omani rial', '.ع.ر'),
  ('PAB', 'Panamanian balboa', 'B/.'),
  ('PEN', 'Peruvian sol', 'S/.'),
  ('PGK', 'Papua New Guinean kina', 'K'),
  ('PHP', 'Philippine peso', '₱'),
  ('PKR', 'Pakistani rupee', '₨'),
  ('PLN', 'Polish złoty', 'zł'),
  ('PYG', 'Paraguayan guarani', '₲'),
  ('QAR', 'Qatari riyal', 'ق.ر'),
  ('RON', 'Romanian leu', 'lei'),
  ('RSD', 'Serbian dinar', 'din'),
  ('RUB', 'Russian ruble', '₽'),
  ('RWF', 'Rwandan franc', 'FRw'),
  ('SAR', 'Saudi riyal', '﷼'),
  ('SBD', 'Solomon Islands dollar', 'Si$'),
  ('SCR', 'Seychellois rupee', 'SRe'),
  ('SDG', 'Sudanese pound', '.س.ج'),
  ('SEK', 'Swedish krona', 'ko'),
  ('SGD', 'Singapore dollar', '$'),
  ('SHP', 'Saint Helena pound', '£'),
  ('SLL', 'Sierra Leonean leone', 'Le'),
  ('SOS', 'Somali shilling', 'Sh.so.'),
  ('SRD', 'Surinamese dollar', '$'),
  ('SSP', 'South Sudanese pound', '£'),
  ('STN', 'Dobra', 'Db'),
  ('SYP', 'Syrian pound', 'LS'),
  ('SZL', 'Lilangeni', 'E'),
  ('THB', 'Thai baht', '฿'),
  ('TJS', 'Tajikistani somoni', 'SM'),
  ('TMT', 'Turkmenistan manat', 'T'),
  ('TND', 'Tunisian dinar', 'ت.د'),
  ('TOP', 'Tongan paʻanga', '$'),
  ('TRY', 'Turkish lira', '₺'),
  ('TTD', 'Trinidad and Tobago dollar', '$'),
  ('TWD', 'New Taiwan dollar', '$'),
  ('TZS', 'Tanzanian shilling', 'TSh'),
  ('UAH', 'Ukrainian hryvnia', '₴'),
  ('UGX', 'Ugandan shilling', 'USh'),
  ('USD', 'United States dollar', '$'),
  ('UYU', 'Uruguayan peso', '$'),
  ('UZS', 'Uzbekistani soʻm', 'лв'),
  ('VES', 'Bolívar', 'Bs'),
  ('VND', 'Vietnamese đồng', '₫'),
  ('VUV', 'Vanuatu vatu', 'VT'),
  ('WST', 'Samoan tālā', 'SAT'),
  ('XAF', 'Central African CFA franc', 'FCFA'),
  ('XCD', 'Eastern Caribbean dollar', '$'),
  ('XOF', 'West African CFA franc', 'CFA'),
  ('XPF', 'CFP franc', '₣'),
  ('YER', 'Yemeni rial', '﷼'),
  ('ZAR', 'South African rand', 'R'),
  ('ZMW', 'Zambian kwacha', 'ZK'),
  ('ZWL', 'Zimbabwe Dollar', '$')
on conflict (code) do update set
  name = excluded.name,
  symbol = excluded.symbol;
