flyway.locations=filesystem:/flyway/db/migrations
flyway.sqlMigrationSuffixes=.sql

flyway.table=flyway_schema_history
flyway.schemas=public

flyway.validateMigrationNaming=true
flyway.outOfOrder=false